name: build
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: versions
        run: |
          echo "echo node=$(jq -r '.volta.node' package.json)" >> $GITHUB_OUTPUT

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - run: |
          yarn test

      - run: |
          yarn pack

      - uses: actions/upload-artifact@v3.1.1
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
