name: build
on:
  push:
    branches:
      - main
      - release/**
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - id: versions
        run: |
          echo "::set-output name=node::$(jq -r '.volta.node' package.json)"

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ steps.versions.outputs.node }}
          cache: 'yarn'

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile

      - run: |
          yarn test

      - name: build (and run size-limit)
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          build_script: size-limit-build
          skip_step: install

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ github.sha }}
          path: |
            ${{ github.workspace }}/*.tgz
